Add support for Tglx1 bindings.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,13 +1,13 @@
 #!/bin/sh
-# This script is only used for developement. It is removed by the 
-# distribution process. 
+# This script is only used for developement. It is removed by the
+# distribution process.
 
 set -e
 
 OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -tag annot -classic-display \
                           -use-ocamlfind"}
 
-action () 
+action ()
 {
     case $1 in
       default)      $OCAMLBUILD $* ;;
@@ -22,31 +22,36 @@ action ()
                     ./apiquery.native -ml -api gles2.0 > src/tgles2.ml
                     ./apiquery.native -mli -api gles3.0 > src/tgles3.mli
                     ./apiquery.native -ml -api gles3.0 > src/tgles3.ml
+                    ./apiquery.native -mli -api glx1.4 support/glx.xml > src/tglx1.mli
+                    ./apiquery.native -ml -api glx1.4 support/glx.xml > src/tglx1.ml
                     ;;
       tgls)         $OCAMLBUILD \
                     tgl3.cmxa dlltgl3.so \
                     tgl4.cmxa dlltgl4.so \
                     tgles2.cmxa dlltgles2.so \
-                    tgles3.cmxa dlltgles3.so 
+                    tgles3.cmxa dlltgles3.so \
+                    tglx1.cmxa dlltglx1.so
                     ;;
       doc)          shift; pkg-doc $* doc/api-dev.docdir ;;
       clean)        $OCAMLBUILD -clean
                     rm -f src/tgl3.mli src/tgl3.ml src/tgl4.mli src/tgl4.ml \
                           src/tgles2.mli src/tgles2.ml src/tgles3.mli \
-                          src/tgles3.ml
+                          src/tgles3.ml src/tglx1.ml
                     ;;
       *)            $OCAMLBUILD $* ;;
     esac
-} 
+}
 
 check_reg ()
 {
-    if [ ! -f "support/gl.xml" ]; then 
-        echo "Missing file support/gl.xml, see DEVEL.md"
-        exit 1
-    fi
+    for file in gl glx; do
+        if [ ! -f "support/$file.xml" ]; then
+            echo "Missing file support/$file.xml, see DEVEL.md"
+            exit 1
+        fi
+    done
 }
 
-if [ $# -eq 0 ]; 
-then action default ; 
+if [ $# -eq 0 ];
+then action default ;
 else action $*; fi
